project:
  type: website

website:
  title: "Hamza ES-SAMAALI"
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - icon: github
        href: https://github.com/HaoES
      - icon: twitter
        href: https://twitter.com/0Kiriyama
      - icon: linkedin
        href: https://www.linkedin.com/in/hamza-es/
format:
  html:
    theme: cosmo
    css: styles.css



