project:
  type: website

website:
  title: "Hamza's Blog"
  google-analytics: "G-RL9R6GRFLC"
  navbar:
    right:
      - text: About
        href: about.qmd 
      - icon: github
        href: https://github.com/HaoES
      - icon: linkedin
        href: https://www.linkedin.com/in/hamza-es/
  
format:
  html:
    theme: theme.scss



